FROM python:3.7.6-stretch

RUN pip install pip --upgrade
RUN pip install ansible
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y && \
    apt install -y openssh-client && \
    apt install -y openssh-server && \
    apt-get install -y sshpass
ENV ANSIBLE_HOST_KEY_CHECKING=False
WORKDIR /work