---
- hosts: targets
  become: yes
  gather_facts: yes
  tasks:

    - name: install apache2
      apt: 
        name: apache2
        update_cache: yes
        state: latest
    
    - name: Start apache2
      command: apache2ctl start
  
    - name: install package
      package:
        name:
          - curl
      